import type { FinanceState } from "./finance-domain";

export const defaultCategories = [
  "Salário",
  "Moradia",
  "Alimentação",
  "Transporte",
  "Saúde",
  "Casa e serviços",
  "Assinaturas",
  "Compras",
  "Lazer",
  "Educação",
  "Profissional",
  "Viagens",
  "Impostos",
  "Outros",
];

export const initialFinanceState: FinanceState = {
  householdName: "Kim & Alexandre",
  people: [
    { id: "kim", name: "Kim", monthlyIncomeCents: 4_000_000, color: "#7142dd" },
    {
      id: "alexandre",
      name: "Alexandre",
      monthlyIncomeCents: 1_029_868,
      color: "#45a68d",
    },
  ],
  categories: defaultCategories,
  transactions: [
    {
      id: "salary-kim",
      owner: "kim",
      kind: "income",
      description: "Salário Kim",
      category: "Salário",
      amountCents: 4_000_000,
      transactionDate: "2026-08-05",
      status: "paid",
      source: "manual",
    },
    {
      id: "salary-alexandre",
      owner: "alexandre",
      kind: "income",
      description: "Salário Alexandre",
      category: "Salário",
      amountCents: 1_029_868,
      transactionDate: "2026-08-05",
      status: "paid",
      source: "manual",
    },
    {
      id: "rent-august",
      owner: "joint",
      kind: "expense",
      description: "Aluguel",
      category: "Moradia",
      amountCents: 500_000,
      transactionDate: "2026-08-28",
      status: "pending",
      source: "manual",
    },
    {
      id: "vivo-august",
      owner: "joint",
      kind: "expense",
      description: "Vivo",
      category: "Casa e serviços",
      amountCents: 22_047,
      transactionDate: "2026-08-12",
      status: "paid",
      source: "email",
    },
    {
      id: "totalpass-august",
      owner: "kim",
      kind: "expense",
      description: "TotalPass",
      category: "Saúde",
      amountCents: 19_990,
      transactionDate: "2026-08-15",
      status: "paid",
      source: "email",
    },
    {
      id: "claro-august",
      owner: "alexandre",
      kind: "expense",
      description: "Claro",
      category: "Casa e serviços",
      amountCents: 9_990,
      transactionDate: "2026-08-16",
      status: "paid",
      source: "email",
    },
    {
      id: "contabilizei-august",
      owner: "kim",
      kind: "expense",
      description: "Contabilizei",
      category: "Profissional",
      amountCents: 19_500,
      transactionDate: "2026-08-20",
      status: "paid",
      source: "email",
    },
    {
      id: "galdan-august",
      owner: "joint",
      kind: "expense",
      description: "GALDAN",
      category: "Assinaturas",
      amountCents: 14_990,
      transactionDate: "2026-08-21",
      status: "paid",
      source: "email",
    },
    {
      id: "google-ai-august",
      owner: "kim",
      kind: "expense",
      description: "Google AI Plus",
      category: "Assinaturas",
      amountCents: 4_999,
      transactionDate: "2026-08-22",
      status: "paid",
      source: "email",
    },
    {
      id: "apple-tv-august",
      owner: "joint",
      kind: "expense",
      description: "Apple TV",
      category: "Assinaturas",
      amountCents: 2_990,
      transactionDate: "2026-08-23",
      status: "paid",
      source: "email",
    },
  ],
  accounts: [],
  cards: [],
  debts: [
    {
      id: "rent-debt",
      owner: "joint",
      description: "Aluguel de agosto",
      totalCents: 500_000,
      installmentCents: 500_000,
      installmentCurrent: 1,
      installmentTotal: 1,
      dueDate: "2026-08-28",
      status: "pending",
      category: "Moradia",
    },
  ],
  budgets: [],
  goals: [],
  recurrences: [
    {
      id: "rec-vivo",
      owner: "joint",
      description: "Vivo",
      category: "Casa e serviços",
      amountCents: 22_047,
      kind: "expense",
      frequency: "monthly",
      nextDate: "2026-09-12",
      active: true,
    },
    {
      id: "rec-totalpass",
      owner: "kim",
      description: "TotalPass",
      category: "Saúde",
      amountCents: 19_990,
      kind: "expense",
      frequency: "monthly",
      nextDate: "2026-09-15",
      active: true,
    },
    {
      id: "rec-claro",
      owner: "alexandre",
      description: "Claro",
      category: "Casa e serviços",
      amountCents: 9_990,
      kind: "expense",
      frequency: "monthly",
      nextDate: "2026-09-16",
      active: true,
    },
    {
      id: "rec-contabilizei",
      owner: "kim",
      description: "Contabilizei",
      category: "Profissional",
      amountCents: 19_500,
      kind: "expense",
      frequency: "monthly",
      nextDate: "2026-09-20",
      active: true,
    },
    {
      id: "rec-galdan",
      owner: "joint",
      description: "GALDAN",
      category: "Assinaturas",
      amountCents: 14_990,
      kind: "expense",
      frequency: "monthly",
      nextDate: "2026-09-21",
      active: true,
    },
    {
      id: "rec-google",
      owner: "kim",
      description: "Google AI Plus",
      category: "Assinaturas",
      amountCents: 4_999,
      kind: "expense",
      frequency: "monthly",
      nextDate: "2026-09-22",
      active: true,
    },
    {
      id: "rec-apple",
      owner: "joint",
      description: "Apple TV",
      category: "Assinaturas",
      amountCents: 2_990,
      kind: "expense",
      frequency: "monthly",
      nextDate: "2026-09-23",
      active: true,
    },
  ],
  invoices: [],
  split: { method: "proportional", kimPercent: 79.52, alexandrePercent: 20.48 },
};
